SELECT * FROM MENU_MA ORDER BY MENU_NO;

UPDATE MENU_MA SET MENU_INTRO = '이건 삭제할 거' WHERE MENU_NO = 82;

UPDATE MENU_MA SET MENU_NM='삭제연습'WHERE MENU_NO = 82;

INSERT INTO MENU_MA (MENU_NO, MENU_NM, MENU_INTRO, MENU_PRI, DEL_YN) VALUES(MENU_MA_SEQ.NEXTVAL,'삭제용', '삭제 할 것', 12000, DEFAULT);

DELETE FROM MENU_MA WHERE MENU_NO = 101;



SELECT * FROM ALL_TABLES WHERE OWNER = 'KDW';
SELECT * FROM ORD_MA;

CREATE USER STUDY IDENTIFIED BY RLAEHDDNR12;

GRANT DBA TO STUDY;

CONN STUDY
SELECT * FROM CUS_MA;
SELECT CUS_NO, CUS_NM FROM CUS_MA WHERE CUS_ID = 'shuai1593' AND CUS_PASS = 'rlaehddnr12';
SELECT CUS_NO, CUS_NM FROM CUS_MA WHERE CUS_ID = 'kdw0725' AND CUS_PASS = 'rlaehddnr12';

SELECT CUS_NO, CUS_NM, ACC_POINT, ACC_DATE FROM POINT p JOIN CUS_MA  C ON C.CUS_N0 = P.CUS_NO;