CREATE TABLE RECIPE(
    REC_NO NUMBER(4) PRIMARY KEY,
    MENU_NO NUMBER(4) NOT NULL,
    FURN_NO NUMBER(4) NOT NULL,
    REC_ING VARCHAR(1000) NOT NULL,
    DEL_YN VARCHAR(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE FURN_MA(
    FURN_NO NUMBER(4) PRIMARY KEY,
    FURN_TYPE VARCHAR2(100) NOT NULL,
    FURN_NM VARCHAR2(100) NOT NULL,
    FURN_HOME VARCHAR2(100) NOT NULL,
    FURN_REM NUMBER NOT NULL,
    EXPIR_DATE DATE NOT NULL,
    OPEN_DATE DATE,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE ORD_MA(
    ORD_NO NUMBER(4) PRIMARY KEY,
    FURN_NO NUMBER(4) NOT NULL,
    STO_NO NUMBER(4) NOT NULL,
    ORD_AMT NUMBER NOT NULL,
    DIS_AMT NUMBER,
    ORD_PRI NUMBER NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE MENU_MA(
    MENU_NO NUMBER(4) PRIMARY KEY,
    MENU_NM VARCHAR2(100) NOT NULL,
    MENU_INTRO VARCHAR2(1000) NOT NULL,
    MENU_PRI NUMBER NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE DEV_MENU(
    MENU_NO NUMBER(4) NOT NULL,
    TEST_COUNT NUMBER NOT NULL,
    EMP_NO NUMBER(4) NOT NULL,
    DEV_DATE DATE DEFAULT SYSDATE NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE INTE_MA(
    INTE_NO NUMBER(4) PRIMARY KEY,
    INTE_NM VARCHAR2(100) NOT NULL,
    INTE_TYPE VARCHAR2(100) NOT NULL,
    INTE_LOC VARCHAR2(100) NOT NULL,
    STO_NO NUMBER(4) NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE STO_MA(
    STO_NO NUMBER(4) PRIMARY KEY,
    STO_NM VARCHAR2(100) NOT NULL,
    STO_LOC VARCHAR2(100) NOT NULL,
    STO_SEAT NUMBER NOT NULL,
    STO_GRD  VARCHAR2(100) NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE SELL_MENU(
    SELL_NO NUMBER(4) PRIMARY KEY,
    SELL_DATE DATE DEFAULT SYSDATE NOT NULL,
    DIS_YN VARCHAR2(4) DEFAULT 'N' NOT NULL,
    MENU_NO NUMBER(4) NOT NULL,
    CUS_NO NUMBER(4),
    EMP_NO NUMBER(4) NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL,
    BILL_NO NUMBER(4) NOT NULL);

CREATE TABLE EMP_MA(
    EMP_NO NUMBER(4) PRIMARY KEY,
    EMP_NM VARCHAR2(100) NOT NULL,
    EMP_GRD VARCHAR2(100) NOT NULL,
    HIRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    FIRE_DATE DATE,
    STO_NO NUMBER(4) NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE VAC_MA(
    VAC_NO NUMBER(4) PRIMARY KEY,
    EMP_NO NUMBER(4) NOT NULL,
    VAC_TYPE VARCHAR2(20) NOT NULL,
    VAC_DATE DATE NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE CUS_MA(
    CUS_NO NUMBER(4) PRIMARY KEY,
    CUS_NM VARCHAR2(100) NOT NULL,
    CUS_ID VARCHAR2(20) NOT NULL,
    CUS_PASS VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(15) NOT NULL,
    LAST_VISIT DATE,
    CAR_NUM_1 VARCHAR2(20),
    CAR_NUM_2 VARCHAR2(20),
    GRD_NO NUMBER(4) NOT NULL,
    APP_DATE DATE DEFAULT SYSDATE NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE POINT(
    POINT_NO NUMBER(4) PRIMARY KEY,
    CUS_NO NUMBER(4) NOT NULL,
    ACC_POINT NUMBER NOT NULL,
    ACC_DATE DATE DEFAULT SYSDATE NOT NULL,
    EMP_NO NUMBER(4) NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);

CREATE TABLE TNA_MA(
    TNA_NO NUMBER(4) PRIMARY KEY,
    ATT_DATE DATE DEFAULT SYSDATE NOT NULL,
    COL_DATE DATE DEFAULT SYSDATE,
    EMP_NO NUMBER(4) NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE SALARY(
    SAL_NO NUMBER(4) PRIMARY KEY,
    EMP_NO NUMBER(4) NOT NULL,
    SAL_DATE DATE NOT NULL,
    SAL_AMT NUMBER NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE GRADE(
    GRD_NO NUMBER(4) PRIMARY KEY,
    GRD_NM VARCHAR2(100) NOT NULL,
    GRD_BENE VARCHAR2(1000) NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE CAL_FEE(
    CAL_NO NUMBER(4) PRIMARY KEY,
    CUS_NO NUMBER(4),
    PARK_NO NUMBER(4) NOT NULL,
    FEE NUMBER NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE PARK_MA(
    PARK_NO NUMBER(4) PRIMARY KEY,
    CAR_NO VARCHAR2(20) NOT NULL,
    ENTRY_TM DATE DEFAULT SYSDATE NOT NULL,
    EXIT_TM DATE,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
CREATE TABLE PROF_MA(
    CAL_DATE DATE DEFAULT SYSDATE NOT NULL,
    PROFIT NUMBER NOT NULL,
    EXPENCES NUMBER NOT NULL,
    DEL_YN VARCHAR2(4) DEFAULT 'N' NOT NULL);
    
ALTER TABLE RECIPE
    ADD CONSTRAINT REC_MENU_NO_FK FOREIGN KEY(MENU_NO) REFERENCES MENU_MA(MENU_NO);
ALTER TABLE RECIPE
    ADD CONSTRAINT REC_FURN_NO_FK FOREIGN KEY(FURN_NO) REFERENCES FURN_MA(FURN_NO);

ALTER TABLE ORD_MA
    ADD CONSTRAINT ORD_FURN_NO_FK FOREIGN KEY(FURN_NO) REFERENCES FURN_MA(FURN_NO);
ALTER TABLE ORD_MA
    ADD CONSTRAINT ORD_STO_NO_FK FOREIGN KEY(STO_NO) REFERENCES STO_MA(STO_NO);
    
ALTER TABLE DEV_MENU
    ADD CONSTRAINT DEV_EMP_NO_FK FOREIGN KEY(EMP_NO) REFERENCES EMP_MA(EMP_NO);
    
ALTER TABLE INTE_MA
    ADD CONSTRAINT INTE_STO_NO_FK FOREIGN KEY(STO_NO) REFERENCES STO_MA(STO_NO);
    
ALTER TABLE SELL_MENU
    ADD CONSTRAINT SELL_MENU_NO_FK FOREIGN KEY(MENU_NO) REFERENCES MENU_MA(MENU_NO);
ALTER TABLE SELL_MENU
    ADD CONSTRAINT SELL_CUS_NO_FK FOREIGN KEY(CUS_NO) REFERENCES CUS_MA(CUS_NO);
ALTER TABLE SELL_MENU
    ADD CONSTRAINT SELL_EMP_NO_FK FOREIGN KEY(EMP_NO) REFERENCES EMP_MA(EMP_NO);
    
ALTER TABLE EMP_MA
    ADD CONSTRAINT EMP_STO_NO_FK FOREIGN KEY(STO_NO) REFERENCES STO_MA(STO_NO);

ALTER TABLE VAC_MA
    ADD CONSTRAINT VAC_EMP_NO_FK FOREIGN KEY(EMP_NO) REFERENCES EMP_MA(EMP_NO);
    
ALTER TABLE CUS_MA
    ADD CONSTRAINT CUS_GRD_NO_FK FOREIGN KEY(GRD_NO) REFERENCES GRADE(GRD_NO);

ALTER TABLE POINT
    ADD CONSTRAINT POINT_CUS_NO_FK FOREIGN KEY(CUS_NO) REFERENCES CUS_MA(CUS_NO);
ALTER TABLE POINT
    ADD CONSTRAINT POINT_EMP_NO_FK FOREIGN KEY(EMP_NO) REFERENCES EMP_MA(EMP_NO);

ALTER TABLE TNA_MA
    ADD CONSTRAINT TNA_EMP_NO_FK FOREIGN KEY(EMP_NO) REFERENCES EMP_MA(EMP_NO);
    
ALTER TABLE SALARY
    ADD CONSTRAINT SAL_EMP_NO_FK FOREIGN KEY(EMP_NO) REFERENCES EMP_MA(EMP_NO);

ALTER TABLE CAL_FEE
    ADD CONSTRAINT CAL_CUS_NO_FK FOREIGN KEY(CUS_NO) REFERENCES CUS_MA(CUS_NO);
ALTER TABLE CAL_FEE
    ADD CONSTRAINT CAL_PARK_NO_FK FOREIGN KEY(PARK_NO) REFERENCES PARK_MA(PARK_NO);
    
CREATE SEQUENCE INTE_MA_SEQ; 
CREATE SEQUENCE VAC_MA_SEQ;
CREATE SEQUENCE TNA_MA_SEQ;
CREATE SEQUENCE SALARY_SEQ;
CREATE SEQUENCE ORD_MA_SEQ;
CREATE SEQUENCE STO_MA_SEQ;
CREATE SEQUENCE EMP_MA_SEQ;
CREATE SEQUENCE POINT_SEQ;
CREATE SEQUENCE FURN_MA_SEQ;
CREATE SEQUENCE CUS_MA_SEQ;
CREATE SEQUENCE CAL_FEE_SEQ;
CREATE SEQUENCE SELL_MENU_SEQ;
CREATE SEQUENCE BILL_NO_SEQ;
CREATE SEQUENCE RECIPE_SEQ;
CREATE SEQUENCE GRADE_SEQ;
CREATE SEQUENCE PARK_MA_SEQ;
CREATE SEQUENCE MENU_MA_SEQ;

DROP SEQUENCE INTE_MA_SEQ; 
DROP SEQUENCE VAC_MA_SEQ;
DROP SEQUENCE TNA_MA_SEQ;
DROP SEQUENCE SALARY_SEQ;
DROP SEQUENCE ORD_MA_SEQ;
DROP SEQUENCE STO_MA_SEQ;
DROP SEQUENCE EMP_MA_SEQ;
DROP SEQUENCE POINT_SEQ;
DROP SEQUENCE FURN_MA_SEQ;
DROP SEQUENCE CUS_MA_SEQ;
DROP SEQUENCE CAL_FEE_SEQ;
DROP SEQUENCE SELL_MENU_SEQ;
DROP SEQUENCE BILL_NO_SEQ;
DROP SEQUENCE RECIPE_SEQ;
DROP SEQUENCE GRADE_SEQ;
DROP SEQUENCE PARK_MA_SEQ;
DROP SEQUENCE MENU_MA_SEQ;

DROP TABLE PROF_MA CASCADE CONSTRAINTS;
DROP TABLE CAL_FEE CASCADE CONSTRAINTS;
DROP TABLE PARK_MA CASCADE CONSTRAINTS;
DROP TABLE DEV_MENU CASCADE CONSTRAINTS;
DROP TABLE RECIPE CASCADE CONSTRAINTS;
DROP TABLE ORD_MA CASCADE CONSTRAINTS;
DROP TABLE FURN_MA CASCADE CONSTRAINTS;
DROP TABLE SELL_MENU CASCADE CONSTRAINTS;
DROP TABLE POINT CASCADE CONSTRAINTS;
DROP TABLE CUS_MA CASCADE CONSTRAINTS;
DROP TABLE GRADE CASCADE CONSTRAINTS;
DROP TABLE MENU_MA CASCADE CONSTRAINTS;
DROP TABLE SALARY CASCADE CONSTRAINTS;
DROP TABLE TNA_MA CASCADE CONSTRAINTS;
DROP TABLE VAC_MA CASCADE CONSTRAINTS;
DROP TABLE INTE_MA CASCADE CONSTRAINTS;
DROP TABLE EMP_MA CASCADE CONSTRAINTS;
DROP TABLE STO_MA CASCADE CONSTRAINTS;

