ALTER TABLE SELL_MENU
ADD BILL_NO NUMBER(4) NOT NULL;

DESC SELL_MENU;

CREATE SEQUENCE SELL_MENU_SEQ;
DROP SEQUENCE SELL_MENU_SEQ;

CREATE SEQUENCE SALARY_SEQ;
SELECT * FROM SALARY;

CREATE SEQUENCE EMP_MA_SEQ;
SELECT * FROM EMP_MA;
TRUNCATE TABLE EMP_MA;
ALTER TABLE EMP_MA
MODIFY EMP_GRD VARCHAR2(100);
CREATE SEQUENCE EMP_MA_SEQ;
DROP SEQUENCE EMP_MA_SEQ;
select * from emp_ma;
select * from salary;

create sequence tna_ma_seq;
DROP SEQUENCE TNA_MA_SEQ;

SELECT * FROM TNA_MA;

SELECT * FROM VAC_MA;
CREATE SEQUENCE VAC_MA_SEQ;
DESC VAC_MA;
ALTER TABLE VAC_MA
MODIFY VAC_TYPE VARCHAR2(0);

SELECT * FROM inte_ma;
DESC INTE_MA;
ALTER TABLE INTE_MA
MODIFY INTE_LOC VARCHAR2(100);
CREATE SEQUENCE INTE_MA_SEQ;
CREATE SEQUENCE ORD_MA_SEQ;



SELECT * FROM STO_MA;
SELECT * FROM POINT;
CREATE SEQUENCE POINT_SEQ;
SELECT * FROM CUS_MA;
DROP SEQUENCE EMP_MA_SEQ;
CREATE SEQUENCE EMP_MA_SEQ
START WITH 21;
SELECT * FROM GRADE;
SELECT * FROM EMP_MA;

CREATE SEQUENCE CAL_FEE_SEQ;
SELECT * FROM CAL_FEE;

CREATE SEQUENCE SELL_MENU_SEQ;
SELECT * FROM SELL_MENU;

CREATE SEQUENCE BILL_NO_SEQ;

SELECT * FROM SELL_MENU;
SELECT * FROM ORD_MA;
SELECT * FROM FURN_MA;
SELECT * FROM STO_MA;

ALTER TABLE RECIPE
MODIFY REC_ING VARCHAR2(1000);

SELECT * FROM RECIPE;
DESC FURN_MA;
CREATE SEQUENCE RECIPE_SEQ;

SELECT * FROM DEV_MENU;
