SELECT * FROM TAB;
SELECT 'ANALYZE TABLE ' || TNAME || ' COMPUTE STATISTICS;' FROM TAB;

ANALYZE TABLE RECIPE COMPUTE STATISTICS;
ANALYZE TABLE MENU_MA COMPUTE STATISTICS;
ANALYZE TABLE ORD_MA COMPUTE STATISTICS;
ANALYZE TABLE FURN_MA COMPUTE STATISTICS;
ANALYZE TABLE DEV_MENU COMPUTE STATISTICS;
ANALYZE TABLE INTE_MA COMPUTE STATISTICS;
ANALYZE TABLE STO_MA COMPUTE STATISTICS;
ANALYZE TABLE EMP_MA COMPUTE STATISTICS;
ANALYZE TABLE SELL_MENU COMPUTE STATISTICS;
ANALYZE TABLE VAC_MA COMPUTE STATISTICS;
ANALYZE TABLE CUS_MA COMPUTE STATISTICS;
ANALYZE TABLE POINT COMPUTE STATISTICS;
ANALYZE TABLE TNA_MA COMPUTE STATISTICS;
ANALYZE TABLE SALARY COMPUTE STATISTICS;
ANALYZE TABLE GRADE COMPUTE STATISTICS;
ANALYZE TABLE CAL_FEE COMPUTE STATISTICS;
ANALYZE TABLE PARK_MA COMPUTE STATISTICS;
ANALYZE TABLE PROF_MA COMPUTE STATISTICS;

SELECT * FROM ALL_TABLES A WHERE OWNER = 'KDW';
SELECT a.num_rows, A.* FROM ALL_TABLES A WHERE A.OWNER = 'KDW';
SELECT * FROM furn_ma;

DELETe RECIPE;
CREATE SEQUENCE recipe_SEQ;

COMMENT ON TABLE CUS_MA IS '고객관리';
COMMENT ON COLUMN CUS_MA.CUS_NO IS '고객번호';

DESC CUS_MA;

SELECT 'COMMENT ON TABLE '|| TABLE_NAME|| ' IS '''';'
FROM TABS;

SELECT 'COMMENT ON COLUMN '|| TABLE_NAME|| '.'|| COLUMN_NAME||' IS  '''';'
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'KDW'
;

COMMENT ON TABLE PROF_MA IS '정산';
COMMENT ON TABLE PARK_MA IS '주차관리';
COMMENT ON TABLE CAL_FEE IS '요금정산';
COMMENT ON TABLE GRADE IS '등급';
COMMENT ON TABLE SALARY IS '월급';
COMMENT ON TABLE TNA_MA IS '';
COMMENT ON TABLE POINT IS '';
COMMENT ON TABLE CUS_MA IS '';
COMMENT ON TABLE VAC_MA IS '';
COMMENT ON TABLE SELL_MENU IS '';
COMMENT ON TABLE EMP_MA IS '';
COMMENT ON TABLE STO_MA IS '';
COMMENT ON TABLE INTE_MA IS '';
COMMENT ON TABLE DEV_MENU IS '';
COMMENT ON TABLE FURN_MA IS '';
COMMENT ON TABLE ORD_MA IS '';
COMMENT ON TABLE MENU_MA IS '';
COMMENT ON TABLE RECIPE IS '';